set guifont=Source\ Code\ Pro\ 9
set guioptions-=r " no right scrollbar
set guioptions-=L " no left scrollbar
set guioptions-=T " no toolbar
set guioptions+=c " use console dialogs instead of popups
set guioptions-=m " no menubar
