" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
set shell=/bin/bash

if filereadable($HOME . '/.config/nvim/init.vim')
  source ~/.config/nvim/init.vim
  finish
endif

" Plugins (using vim-plug) {{{
" automatically install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
" ui
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" utilities
Plug 'ConradIrwin/vim-bracketed-paste' " automatic :set paste
Plug 'ntpeters/vim-better-whitespace'
Plug 'rking/ag.vim'
Plug 'scrooloose/nerdcommenter'
Plug 'sjl/gundo.vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-unimpaired'
Plug 'wesQ3/vim-windowswap'

" languages
Plug 'chrisbra/csv.vim'
Plug 'mlr-msft/vim-loves-dafny', {'for': 'dafny'}
Plug 'tikhomirov/vim-glsl'
Plug 'tomvanderlee/vim-kerboscript'
Plug 'harenome/vim-mipssyntax'
Plug 'evanmiller/nginx-vim-syntax'
Plug 'fs111/pydoc.vim'
Plug 'tmux-plugins/vim-tmux'
Plug 'seanpianka/vim-z80'

Plug 'sheerun/vim-polyglot'

" Haskell
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
  Plug 'eagletmt/ghcmod-vim'
Plug 'eagletmt/neco-ghc'
Plug 'vim-scripts/haskell.vim'
Plug 'vim-scripts/cabal.vim'

" Lua
Plug 'raymond-w-ko/vim-lua-indent' " fix indentation
Plug 'xolox/vim-misc'
  Plug 'xolox/vim-lua-ftplugin'

" PHP
Plug '2072/PHP-Indenting-for-VIm'
Plug 'StanAngeloff/php.vim'

" completion
Plug 'ervandew/supertab'
Plug 'Shougo/javacomplete'

function! BuildYCM(info)
  " info is a dictionary with 3 fields
  " - name:   name of the plugin
  " - status: 'installed', 'updated', or 'unchanged'
  " - force:  set on PlugInstall! or PlugUpdate!
  if a:info.status == 'installed' || a:info.force
    !./install.py --clang-completer
  endif
endfunction
if hostname() == 'mandelbrot' " only install YCM on mandelbrot
  Plug 'Valloric/YouCompleteMe', { 'do': function('BuildYCM') }
endif

" other
Plug 'christoomey/vim-tmux-navigator'
Plug 'coot/CRDispatcher'
  Plug 'coot/enchantedvim'

call plug#end()
" }}}
" Colors {{{
"set termguicolors
colorscheme molokai     " very nice
set background=dark
syntax enable           " turn syntax highlighting on
set t_ut=               " fix background color erase on terminal
" }}}
" Misc {{{
set backspace=indent,eol,start

set splitbelow          " split in a sensible manner
set splitright

" More effective block editing
set virtualedit=block

" Mark columns 80 and 90, and past 120
let &colorcolumn="80,90,120"

" Decrease delay on escape
set ttimeoutlen=50

" Properly display man pages (in gvim)
" from https://www.guyrutenberg.com/2014/01/03/view-man-pages-properly-in-gvim/
" ==========================
runtime ftplugin/man.vim
if has("gui_running")
  nnoremap K :<C-U>exe "Man" v:count "<C-R><C-W>"<CR>
endif

" }}}
" Spaces and Tabs {{{
set tabstop=2           " number of visual spaces per tab
set softtabstop=2       " number of spaces in tab when editing
set shiftwidth=2        " number of spaces in tab when reindenting
set expandtab           " tabs are spaces

set autoindent          " automatic indentation is nice
" }}}
" UI Config {{{
set ruler               " always show the cursor position
set number              " line numbers
set title               " display a title
set cursorline          " highlight current line

set wildmenu            " standard shell-like path completion
set wildmode=list:longest
set lazyredraw          " redraw only when necessary (faster macros)

set scrolloff=2         " don't let it touch the edge!
if has('mouse')
  set mouse=a             " enable the mouse
  set ttymouse=xterm2     " much faster mouse
endif

" Use mode-dependent cursor
if $TERM !=# 'linux'
  let &t_ti.="\e[1 q"
  let &t_te.="\e[5 q"
  let &t_SI.="\e[5 q"
  let &t_EI.="\e[1 q"
endif

" }}}
" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase          " We don't care about case...
set smartcase           " ...or do we?
" }}}
" Folding {{{
if has('folding')
  set foldenable          " enable folding
  set foldlevelstart=10   " open most folds by default
  set foldnestmax=10      " 10 nested fold max
  set foldmethod=indent   " fold based on indent level
endif
" }}}
" Movement Shortcuts {{{
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" move vertically by visual line
nnoremap j gj
nnoremap k gk

" move to beginning/end of line
nnoremap B ^
nnoremap E $

" }}}
" Leader Shortcuts {{{

" Much more convienient than \
let mapleader = "\<Space>"

" Faster save and quit
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>

" Write, darn you!
nnoremap <Leader>W :w!<CR>
" Die!
nnoremap <Leader>Q :q!<CR>

" za is so awkward
nnoremap <Leader>z za

" Copy and paste to system clipboard with leader
vnoremap <Leader>y "+y
vnoremap <Leader>d "+d
nnoremap <Leader>p "+p
vnoremap <Leader>p "+p
nnoremap <Leader>P "+P
vnoremap <Leader>P "+P

nnoremap <silent> <Leader>h :let @/ = ""<CR>

nnoremap <Leader>n :NERDTreeToggle<CR>
nnoremap <Leader>u :GundoToggle<CR>

" }}}
" Airline {{{
set laststatus=2        " always show the status line
set noshowmode          " airline handles this

let g:airline_theme             = 'powerlineish'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline_powerline_fonts   = 1

" Enable the list of buffers
let g:airline#extensions#tabline#enabled = 1
" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'
" }}}
" Windowswap {{{
" Prevent default bindings
let g:windowswap_map_keys = 0
nnoremap <silent> <leader>wy :call WindowSwap#MarkWindowSwap()<CR>
nnoremap <silent> <leader>wp :call WindowSwap#DoWindowSwap()<CR>
nnoremap <silent> <leader>ww :call WindowSwap#EasyWindowSwap()<CR>

" }}}
" Tmux {{{
""""""""""""""
" tmux fixes "
""""""""""""""
" Handle tmux $TERM issues in vim
"if $TERM =~ '^screen-256color'
"  map <Esc>OH <Home>
"  map! <Esc>OH <Home>
"  map <Esc>OF <End>
"  map! <Esc>OF <End>
"endif
" }}}
" Backups {{{

set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

" }}}
" YouCompleteMe {{{
let g:ycm_extra_conf_globlist = ['/mnt/sdcard/school/data_structures/*','~/projects/advent-of-code/*','~/school/comp_org/*','!~/*']
"let g:ycm_server_keep_logfiles = 0
let g:ycm_semantic_triggers = {'haskell' : ['.']}   " for neco-ghc
" }}}
" NERD Commenter {{{
let g:NERDCustomDelimiters = { 'kerboscript': { 'left': '//' } }
" }}}
" Syntastic {{{
" Tell Syntastic to:
" - check files on save.
" - but only check Dafny files when requested.
let g:syntastic_mode_map = {
        \ "mode": "active",
        \ "passive_filetypes": ["dafny"] }
" }}}

" vim-pydoc
let g:pydoc_highlight=0
let g:pydoc_window_lines=0.5

" better-whitespace
let g:better_whitespace_filetypes_blacklist=['diff', 'gitcommit', 'unite', 'qf', 'help', 'man', 'pydoc']

" Haskell {{{
" ghcmod
let $PATH = $PATH . ':' . expand('~/.local/bin')

" necoghc
let g:haskellmode_completion_ghc = 1
autocmd FileType haskell setlocal omnifunc=necoghc#omnifunc

let g:syntastic_check_on_wq = 0
" }}}

"
" Mostly from http://sheerun.net/2014/03/21/how-to-boost-your-vim-productivity/
"

" vim:foldmethod=marker:foldlevel=0
